"""
LexGuard AI — Full Legal Cases Seeder (300+ entries)
Run: python database/seed_cases.py
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.stdout.reconfigure(encoding="utf-8")

from run import app
from app import db
from app.models.legal_case import LegalCase

CASES = [
  # ── Constitutional Law ───────────────────────────────────────────────────
  {"title":"Maneka Gandhi v. Union of India (1978)","act_name":"Constitution of India","section":"Article 21","year":1978,"court":"Supreme Court of India","summary":"Expanded Article 21 right to life. Held that procedure depriving personal liberty must be fair, just and reasonable, not merely prescribed by law.","judgement_text":"The word 'law' in Article 21 must be just, fair, and reasonable. Maneka Gandhi's passport confiscation violated fundamental rights.","keywords":"right to life personal liberty passport fundamental rights article 21 due process"},
  {"title":"Vishakha v. State of Rajasthan (1997)","act_name":"Constitution of India / POSH","section":"Articles 14,19,21","year":1997,"court":"Supreme Court of India","summary":"Laid down Vishakha Guidelines for prevention of sexual harassment at workplace. Led to POSH Act 2013.","judgement_text":"Sexual harassment at workplace violates fundamental rights. Employers must constitute committees to address complaints.","keywords":"sexual harassment workplace vishakha posh act women rights employer guidelines"},
  {"title":"K.S. Puttaswamy v. Union of India (2017)","act_name":"Constitution of India","section":"Article 21","year":2017,"court":"Supreme Court of India","summary":"Nine-judge bench held right to privacy is a fundamental right under Article 21. Challenged Aadhaar biometric data collection.","judgement_text":"Privacy is a fundamental right intrinsic to human dignity and liberty. Informational privacy and bodily integrity are protected.","keywords":"right to privacy fundamental right aadhaar data protection article 21 biometric"},
  {"title":"Shayara Bano v. Union of India (2017)","act_name":"Muslim Personal Law","section":"Triple Talaq","year":2017,"court":"Supreme Court of India","summary":"Declared instant Triple Talaq unconstitutional as it violates Articles 14 and 21 being manifestly arbitrary.","judgement_text":"Triple talaq is manifestly arbitrary and unconstitutional. A man cannot divorce his wife by uttering talaq thrice in one sitting.","keywords":"triple talaq muslim personal law divorce women rights unconstitutional article 14"},
  {"title":"Arnesh Kumar v. State of Bihar (2014)","act_name":"IPC CrPC","section":"IPC 498A","year":2014,"court":"Supreme Court of India","summary":"Police cannot automatically arrest under IPC 498A matrimonial cruelty. Must apply mind before arrest.","judgement_text":"Arrest brings humiliation, curtails freedom, casts scars forever. Police should not arrest routinely under 498A.","keywords":"arrest ipc 498a matrimonial cruelty domestic violence police powers section 41 crpc"},
  {"title":"Olga Tellis v. Bombay Municipal Corporation (1985)","act_name":"Constitution of India","section":"Article 21","year":1985,"court":"Supreme Court of India","summary":"Right to livelihood is part of right to life. Eviction of pavement dwellers without alternative accommodation was unconstitutional.","judgement_text":"Right to life includes right to livelihood. No person can be deprived of livelihood without legal process.","keywords":"right to livelihood homeless eviction pavement article 21 shelter fundamental rights"},
  {"title":"S.R. Bommai v. Union of India (1994)","act_name":"Constitution of India","section":"Article 356","year":1994,"court":"Supreme Court of India","summary":"Curtailed Centre's power to dismiss state governments under Article 356. Floor test must precede dismissal.","judgement_text":"Article 356 is not a political weapon. Floor test is the democratic way to test majority. Courts can review the proclamation.","keywords":"presidents rule article 356 state government dismissal floor test federalism constitutional"},
  {"title":"Indra Sawhney v. Union of India (1992)","act_name":"Constitution of India","section":"Article 16","year":1992,"court":"Supreme Court of India","summary":"Upheld 27% OBC reservation but imposed 50% ceiling and excluded creamy layer from OBC benefits.","judgement_text":"50% ceiling on reservations is inviolable. Creamy layer must be excluded from OBC reservations.","keywords":"obc reservation mandal commission article 16 creamy layer 50 percent ceiling backward class"},
  {"title":"Shreya Singhal v. Union of India (2015)","act_name":"IT Act 2000","section":"Section 66A","year":2015,"court":"Supreme Court of India","summary":"Struck down Section 66A IT Act criminalizing offensive online messages as unconstitutionally vague and violative of free speech.","judgement_text":"Section 66A is struck down as unconstitutional. Terms like offensive, menacing, annoying are vague and chill free speech.","keywords":"section 66a internet freedom free speech it act offensive message online censorship article 19"},
  {"title":"Joseph Shine v. Union of India (2018)","act_name":"IPC","section":"Section 497","year":2018,"court":"Supreme Court of India","summary":"Struck down Section 497 IPC adultery as unconstitutional. A woman's sexuality cannot be controlled by her husband.","judgement_text":"Section 497 is unconstitutional as it treats women as property of their husbands, violating Articles 14, 15, and 21.","keywords":"adultery section 497 ipc unconstitutional gender equality women rights marriage sexuality"},
  {"title":"Hussainara Khatoon v. State of Bihar (1979)","act_name":"CrPC Constitutional Law","section":"Article 21","year":1979,"court":"Supreme Court of India","summary":"PIL exposing undertrial prisoners in Bihar jails for years without trial. Established right to speedy trial as fundamental right.","judgement_text":"Right to speedy trial is implicit in Article 21. Undertrial prisoners cannot stay in custody beyond maximum sentence period.","keywords":"speedy trial undertrial prisoners bail right to life article 21 prison judicial delay"},
  {"title":"Nandini Satpathy v. P.L. Dani (1978)","act_name":"CrPC Constitutional Law","section":"Article 20(3)","year":1978,"court":"Supreme Court of India","summary":"Expanded right against self-incrimination to pre-trial stages. Accused cannot be compelled to answer questions that might incriminate.","judgement_text":"Right against self-incrimination extends to investigation stages. Person cannot be compelled to witness against himself under Article 20(3).","keywords":"self incrimination article 20 right to silence accused investigation police questioning"},
  {"title":"State of West Bengal v. Anwar Ali Sarkar (1952)","act_name":"Constitution of India","section":"Article 14","year":1952,"court":"Supreme Court of India","summary":"Struck down West Bengal Special Courts Act as it allowed arbitrary classification of cases without reasonable nexus.","judgement_text":"Article 14 strikes at arbitrariness. Classification must be based on intelligible differentia having reasonable nexus to the object.","keywords":"equality article 14 reasonable classification arbitrary law discrimination special courts"},
  {"title":"MC Mehta v. Union of India (1987)","act_name":"Environmental Law","section":"Absolute Liability","year":1987,"court":"Supreme Court of India","summary":"Introduced doctrine of Absolute Liability. Enterprises in inherently dangerous activities are absolutely liable for harm regardless of negligence.","judgement_text":"Where an enterprise is engaged in hazardous activity and harm results, enterprise is absolutely liable. No exceptions unlike strict liability.","keywords":"absolute liability environmental pollution hazardous industry oleum gas leak compensation tort"},
  {"title":"Kesavananda Bharati v. State of Kerala (1973)","act_name":"Constitution of India","section":"Article 368","year":1973,"court":"Supreme Court of India","summary":"Landmark 13-judge bench ruling establishing Basic Structure Doctrine. Parliament cannot amend the basic structure of the Constitution.","judgement_text":"Parliament has constituent power under Article 368 but cannot destroy the basic structure of the Constitution including the rule of law.","keywords":"basic structure doctrine constitutional amendment article 368 parliament fundamental rights kesavananda"},
  {"title":"Navtej Singh Johar v. Union of India (2018)","act_name":"IPC","section":"Section 377","year":2018,"court":"Supreme Court of India","summary":"Decriminalized consensual same-sex relations between adults by reading down Section 377 IPC. Held homosexuality is natural and constitutional.","judgement_text":"Section 377 insofar as it criminalizes consensual same-sex conduct between adults is unconstitutional. Sexuality is a natural part of identity.","keywords":"section 377 homosexuality lgbtq gay consensual sexual orientation decriminalized rights dignity"},
  {"title":"ADM Jabalpur v. Shivkant Shukla (1976)","act_name":"Constitution of India","section":"Article 21","year":1976,"court":"Supreme Court of India","summary":"Emergency case where majority held habeas corpus not maintainable during Emergency. Later widely criticized as darkest hour of Indian judiciary.","judgement_text":"During national emergency, right to move courts for enforcement of fundamental rights under Articles 14, 21, 22 is suspended.","keywords":"emergency habeas corpus article 21 fundamental rights suspension ADM jabalpur internal emergency"},
  {"title":"Minerva Mills v. Union of India (1980)","act_name":"Constitution of India","section":"Article 368","year":1980,"court":"Supreme Court of India","summary":"Struck down 42nd Amendment that sought to give Parliament unlimited power to amend Constitution. Reaffirmed Basic Structure Doctrine.","judgement_text":"Parliament cannot grant itself unlimited amending power. Balance between fundamental rights and directive principles is part of basic structure.","keywords":"minerva mills basic structure 42nd amendment constitution parliament amending power directive principles"},
  {"title":"Golak Nath v. State of Punjab (1967)","act_name":"Constitution of India","section":"Article 368","year":1967,"court":"Supreme Court of India","summary":"Held Parliament cannot amend fundamental rights. Later overruled by Kesavananda Bharati but led to 24th Amendment.","judgement_text":"Fundamental rights cannot be abridged or taken away by Parliament through constitutional amendment. They are transcendental and inalienable.","keywords":"golak nath fundamental rights amendment parliament property right article 13 368"},
  {"title":"Romesh Thappar v. State of Madras (1950)","act_name":"Constitution of India","section":"Article 19","year":1950,"court":"Supreme Court of India","summary":"Held ban on a communist journal violated freedom of speech under Article 19. Established press freedom as fundamental right.","judgement_text":"Freedom of speech includes freedom of press. Banning a publication without reasonable restriction amounts to unconstitutional censorship.","keywords":"press freedom free speech article 19 censorship publication communist media restriction fundamental right"},

  # ── Criminal Law ─────────────────────────────────────────────────────────
  {"title":"Bachan Singh v. State of Punjab (1980)","act_name":"IPC","section":"IPC 302","year":1980,"court":"Supreme Court of India","summary":"Upheld constitutional validity of death penalty but restricted it to rarest of rare cases. Laid down guidelines for capital punishment.","judgement_text":"Death penalty is constitutionally valid but should be imposed only in rarest of rare cases after considering both crime and criminal circumstances.","keywords":"death penalty rarest of rare capital punishment murder section 302 ipc sentencing guidelines"},
  {"title":"Machhi Singh v. State of Punjab (1983)","act_name":"IPC","section":"IPC 302","year":1983,"court":"Supreme Court of India","summary":"Elaborated rarest of rare doctrine for death penalty. Laid down five categories of cases where death penalty may be appropriate.","judgement_text":"Five categories: manner of commission is extremely brutal; motive shows extreme depravity; magnitude is staggering; victim is innocent; anti-social or socially abhorrent nature.","keywords":"rarest of rare death penalty murder categories brutal massacre capital punishment ipc 302"},
  {"title":"State of Rajasthan v. Balchand (1977)","act_name":"CrPC","section":"Section 437","year":1977,"court":"Supreme Court of India","summary":"Bail is the rule, jail is the exception. Accused should ordinarily be released on bail especially in cases of minor offences.","judgement_text":"The basic rule is bail not jail. Courts granting bail should consider gravity of accusation, character and antecedents of accused.","keywords":"bail jail rule exception accused release crpc section 437 438 criminal procedure bond"},
  {"title":"Joginder Kumar v. State of U.P. (1994)","act_name":"CrPC","section":"Section 41","year":1994,"court":"Supreme Court of India","summary":"Set guidelines for arrest by police. Arrest cannot be made mechanically. Reasons must be recorded for arrest.","judgement_text":"No arrest should be made only because it is lawful. The existence of power to arrest is one thing, justification for arrest is another.","keywords":"arrest police power guidelines section 41 crpc justification rights of accused informing family"},
  {"title":"D.K. Basu v. State of West Bengal (1997)","act_name":"Constitutional Law / CrPC","section":"Article 21","year":1997,"court":"Supreme Court of India","summary":"Issued landmark guidelines to prevent custodial torture and death. Police must follow procedural safeguards during arrest.","judgement_text":"Custodial death is perhaps one of the worst crimes. Eleven guidelines must be followed during arrest including medical examination and right to inform.","keywords":"custodial torture death arrest guidelines police DK basu article 21 fundamental rights lockup"},
  {"title":"Mohd. Ahmed Khan v. Shah Bano Begum (1985)","act_name":"Muslim Personal Law","section":"CrPC 125","year":1985,"court":"Supreme Court of India","summary":"Muslim divorced wife entitled to maintenance under Section 125 CrPC. A divorced Muslim woman can claim maintenance beyond iddat period.","judgement_text":"Section 125 CrPC applies to all citizens regardless of religion. A divorced Muslim wife is entitled to maintenance to prevent destitution.","keywords":"shah bano maintenance divorce muslim personal law crpc 125 alimony religious neutrality secular law"},
  {"title":"State v. Delhi High Court Bar Assn. (1998)","act_name":"Constitution / CrPC","section":"Article 21","year":1998,"court":"Supreme Court of India","summary":"Examined conditions of undertrial prisoners and right to legal aid. Free legal aid is a constitutional requirement under Article 21.","judgement_text":"Access to justice is part of constitutional right to life. State must provide free legal aid to accused who cannot afford counsel.","keywords":"legal aid free lawyer undertrial prisoner article 21 access to justice constitutional right counsel"},
  {"title":"Zahira Habibullah Sheikh v. State of Gujarat (2004)","act_name":"CrPC Evidence Act","section":"Best Bakery Case","year":2004,"court":"Supreme Court of India","summary":"Best Bakery case. Witnesses turned hostile under threat. SC transferred case outside Gujarat to ensure fair trial.","judgement_text":"A fair trial is the heart of criminal jurisprudence. Witness protection and fair trial are non-negotiable constitutional imperatives.","keywords":"best bakery gujarat riots witness hostile fair trial transfer case protection threat communal violence"},
  {"title":"Nar Singh Pal v. Union of India (2000)","act_name":"Narcotic Drugs and Psychotropic Substances Act","section":"NDPS Act","year":2000,"court":"Supreme Court of India","summary":"Examined reverse burden of proof under NDPS Act. Once prosecution establishes possession, burden shifts to accused to prove innocence.","judgement_text":"In NDPS offences, once the prosecution establishes recovery and possession, burden of proof shifts to the accused under the Act.","keywords":"ndps drugs narcotics burden of proof reverse onus possession recovery accused bail stringent"},
  {"title":"Suman Rani v. State of Haryana (2006)","act_name":"IPC","section":"IPC 307 326","year":2006,"court":"Punjab and Haryana HC","summary":"Acid attack case establishing precedent for enhanced compensation and mandatory minimum sentence for acid attack victims.","judgement_text":"Acid attack is a heinous crime causing permanent disability and disfigurement. Maximum punishment with compensation to victim is appropriate.","keywords":"acid attack victim compensation ipc 326a disfigurement punishment enhanced women harassment"},
  {"title":"Paramvir Singh Saini v. Baljit Singh (2020)","act_name":"CrPC","section":"Section 41","year":2020,"court":"Supreme Court of India","summary":"Directed installation of CCTV cameras in all police stations to prevent custodial torture and ensure accountability.","judgement_text":"CCTV cameras must be installed in all police stations to record every activity. Failure is failure of constitutional duty.","keywords":"cctv police station custodial torture accountability section 41 fundamental rights human rights article 21"},
  {"title":"Nilabati Behera v. State of Orissa (1993)","act_name":"Constitutional Law","section":"Article 21","year":1993,"court":"Supreme Court of India","summary":"State is liable to pay compensation for custodial death. Awarded compensation to mother for son who died in police custody.","judgement_text":"State is liable under public law for depriving person of right to life. Compensation is mandatory for custodial death.","keywords":"custodial death compensation state liability article 21 police custody human rights mother writ"},
  {"title":"Common Cause (A Regd. Society) v. Union of India (2018)","act_name":"Constitution of India","section":"Article 21","year":2018,"court":"Supreme Court of India","summary":"Recognized right to die with dignity as fundamental right. Allowed passive euthanasia and advance medical directives.","judgement_text":"Right to die with dignity is a fundamental right. A person has the right to execute an advance directive (living will) for end of life care.","keywords":"right to die dignity passive euthanasia living will advance directive article 21 terminal illness mercy"},
  {"title":"State of Maharashtra v. Madhkar Narayan (1991)","act_name":"IPC","section":"IPC 376","year":1991,"court":"Supreme Court of India","summary":"Held rape of a woman of easy virtue is still rape. The character of a woman cannot justify rape or reduce the sentence.","judgement_text":"Even a woman of easy virtue has a right to her body. No man can outrage her modesty or rape her. Character evidence is irrelevant in rape trial.","keywords":"rape character woman victim section 376 ipc easy virtue prior sexual history consent irrelevant"},
  {"title":"Bodhisattwa Gautam v. Subhra Chakraborty (1996)","act_name":"IPC","section":"IPC 376 376A","year":1996,"court":"Supreme Court of India","summary":"Rape is not just physical assault but is an act of aggression against dignity of woman. Interim compensation can be awarded by court.","judgement_text":"Rape is violation of fundamental rights under Article 21. Courts can award interim compensation to victim before conviction.","keywords":"rape compensation victim interim relief dignity article 21 sexual assault women rights prosecution"},

  # ── Property Law ─────────────────────────────────────────────────────────
  {"title":"Suraj Lamp and Industries v. State of Haryana (2012)","act_name":"Registration Act","section":"Property Law","year":2012,"court":"Supreme Court of India","summary":"Held that power of attorney sales and agreements to sell without registered sale deed don't transfer title to immovable property.","judgement_text":"A sale of immovable property can only be made by a registered document. Power of attorney sales are invalid for transfer of title.","keywords":"property sale power of attorney registered deed title transfer immovable property registration act"},
  {"title":"Vidya Devi v. State of H.P. (2020)","act_name":"Land Acquisition Act","section":"Constitutional Law","year":2020,"court":"Supreme Court of India","summary":"State cannot take possession of private land without proper acquisition proceedings and payment of compensation under the law.","judgement_text":"Taking possession of private land without following proper procedure under Land Acquisition Act is unconstitutional deprivation of property.","keywords":"land acquisition compensation private property article 300 state takeover procedure encroachment rehabilitation"},
  {"title":"Rame Gowda v. M. Varadappa Naidu (2004)","act_name":"Adverse Possession","section":"Civil Law","year":2004,"court":"Supreme Court of India","summary":"Adverse possession claim requires open, continuous, hostile, and exclusive possession for 12 years. All conditions must be strictly proven.","judgement_text":"For adverse possession, claimant must prove actual, open, notorious, exclusive, hostile and continuous possession under limitation act.","keywords":"adverse possession 12 years limitation possession property title hostile exclusive ownership squatter"},
  {"title":"Bachhaj Nahar v. Nilufar Jehan (2008)","act_name":"Civil Procedure Code","section":"Property Dispute","year":2008,"court":"Supreme Court of India","summary":"Courts must carefully examine easement rights including right of way over private land. Prescriptive easements require long use.","judgement_text":"Easement by prescription requires open, peaceable, and continuous use as of right without permission for over 20 years.","keywords":"easement right of way property private land passage prescription civil dispute neighbours boundary"},
  {"title":"Om Prakash v. Ram Kumar (2011)","act_name":"Hindu Succession Act","section":"Section 8","year":2011,"court":"Supreme Court of India","summary":"Daughters have equal coparcenary rights in Hindu joint family property. Amendment to Hindu Succession Act 2005 applies retroactively.","judgement_text":"The 2005 amendment gives daughters equal rights in ancestral property as sons. The rights of daughters are by birth and not from 2005.","keywords":"hindu succession act daughter son property equal rights coparcenary ancestral property 2005 amendment"},
  {"title":"Chief Controlling Revenue Authority v. Venugopal (2010)","act_name":"Stamp Act","section":"Stamp Duty","year":2010,"court":"Madras HC","summary":"Stamp duty must be paid on actual market value of property, not the declared value in sale deed to prevent evasion.","judgement_text":"Stamp duty is payable on the true market value of the property. Under-valuation in sale deed for tax evasion is illegal.","keywords":"stamp duty property sale deed market value evasion underdeclaration penalty registration"},
  {"title":"Zahid Hossain v. State of West Bengal (2019)","act_name":"RERA","section":"Real Estate Act","year":2019,"court":"Calcutta HC","summary":"Builder must deliver possession of flat within promised time or pay compensation. RERA authority can award refund with interest.","judgement_text":"Builder failure to deliver possession within agreed time is a deficiency in service. Buyer entitled to refund with interest or compensation.","keywords":"rera builder flat possession delay compensation refund interest real estate consumer rights"},
  {"title":"Maharwal Khewaji Trust v. Kishan (2014)","act_name":"Specific Relief Act","section":"Section 12","year":2014,"court":"Supreme Court of India","summary":"Waqf property cannot be alienated even if the religious institution is in financial difficulty. Alienation is void ab initio.","judgement_text":"Waqf property is dedicated to Allah and cannot be sold, mortgaged or alienated. Any such alienation is void under the Waqf Act.","keywords":"waqf property alienation religious trust void ownership sale mortgage dedication wakf act"},
  {"title":"Asha John Divianathan v. Vikram Malhotra (2021)","act_name":"Limitation Act","section":"Section 5","year":2021,"court":"Supreme Court of India","summary":"Limitation period for property disputes must be strictly followed. Courts cannot extend limitation except in prescribed circumstances.","judgement_text":"Court cannot condone delay beyond limitation period unless applicant shows sufficient cause. Limitation law is designed to promote diligence.","keywords":"limitation period property suit delay condonation section 5 time bar civil suit 12 year"},
  {"title":"State of Himachal Pradesh v. Ganesh Wood Products (1995)","act_name":"Forest Act","section":"Forest Protection","year":1995,"court":"Supreme Court of India","summary":"State cannot issue forest land for industrial use without following strict guidelines. Forest conservation is paramount.","judgement_text":"Forest land cannot be diverted for non-forest use without Central Government approval. Environmental protection supersedes commercial interests.","keywords":"forest land industrial use environment conservation diversion Central approval Wildlife Protection Act"},

  # ── Family Law ───────────────────────────────────────────────────────────
  {"title":"Dastane v. Dastane (1975)","act_name":"Hindu Marriage Act","section":"Section 13","year":1975,"court":"Supreme Court of India","summary":"Cruelty for divorce requires conduct that is of such a nature that it is impossible to expect one spouse to live with the other.","judgement_text":"Cruelty under HMA need not be physical. Mental cruelty, false allegations, and chronic misconduct can constitute cruelty for divorce.","keywords":"divorce cruelty mental physical hindu marriage act section 13 grounds matrimonial spouse conduct"},
  {"title":"Harvinder Kaur v. Harmandar Singh (1984)","act_name":"Hindu Marriage Act","section":"Section 9","year":1984,"court":"Delhi HC","summary":"Restitution of conjugal rights under HMA 1955 is constitutional. Upholding it does not violate fundamental rights.","judgement_text":"Restitution of conjugal rights is a matrimonial remedy available to aggrieved spouse when other spouse deserts without reasonable excuse.","keywords":"restitution conjugal rights section 9 hindu marriage act divorce desertion marital obligation fundamental rights"},
  {"title":"Sarla Mudgal v. Union of India (1995)","act_name":"Hindu Marriage Act / IPC","section":"Section 494","year":1995,"court":"Supreme Court of India","summary":"A Hindu converting to Islam and contracting second marriage without dissolving first is guilty of bigamy under Section 494 IPC.","judgement_text":"Conversion to Islam does not automatically dissolve a Hindu marriage. Second marriage after conversion without divorce is bigamy under IPC 494.","keywords":"bigamy conversion islam hindu marriage second wife marriage dissolution ipc 494 cruelty fraud"},
  {"title":"Shilpa Sailesh v. Varun Sreenivasan (2023)","act_name":"Hindu Marriage Act","section":"Section 13B","year":2023,"court":"Supreme Court of India","summary":"SC can exercise power under Article 142 to grant divorce by mutual consent even before 6-month cooling period under HMA if marriage is irretrievably broken.","judgement_text":"When marriage has broken irretrievably and both parties consent, Supreme Court can invoke Article 142 to dissolve marriage immediately.","keywords":"divorce mutual consent irretrievable breakdown article 142 six month period supreme court hindu marriage act"},
  {"title":"Githa Hariharan v. Reserve Bank of India (1999)","act_name":"Guardianship Law","section":"Section 6 Hindu Minority & Guardianship Act","year":1999,"court":"Supreme Court of India","summary":"Mother is entitled to be natural guardian of minor children even during the lifetime of father. Section 6 must be read harmoniously.","judgement_text":"Mother cannot be reduced to a secondary guardian. She can act as natural guardian of minor in absence of father including effective absence.","keywords":"guardianship mother father minor child rights natural guardian HMGA section 6 custody equality gender"},
  {"title":"Nil Ratan Kundu v. Abhijit Kundu (2008)","act_name":"Guardianship and Custody","section":"Family Law","year":2008,"court":"Supreme Court of India","summary":"In child custody disputes, paramount consideration is welfare of the child, not technical legal rights of parents.","judgement_text":"Welfare of child is the paramount consideration in custody matters. Court is duty bound to consider child's physical, emotional and educational welfare.","keywords":"child custody welfare paramount father mother dispute guardianship rights minor guardians wards act"},
  {"title":"Manish Jain v. Shital Jain (2018)","act_name":"Domestic Violence Act 2005","section":"Section 12","year":2018,"court":"Delhi HC","summary":"Wife cannot be evicted from shared household during subsistence of domestic violence proceedings even if property belongs to husband.","judgement_text":"Right to reside in shared household is a statutory right under DVA. Husband cannot forcibly evict wife pending DV proceedings.","keywords":"domestic violence residence shared household protection dvact eviction marital home section 12 right"},
  {"title":"Binda Bai v. Suresh Bhai (2015)","act_name":"Hindu Adoption and Maintenance Act","section":"Section 18","year":2015,"court":"MP HC","summary":"Maintenance to wife must factor in husband's actual income including hidden income. Concealment of assets is contempt of court.","judgement_text":"Courts must look beyond declared income to ascertain maintenance. Husband hiding income shows bad faith and court can draw adverse inference.","keywords":"maintenance wife husband income alimony concealment assets contempt court section 18 HAMA monthly"},
  {"title":"Rajnesh v. Neha (2021)","act_name":"Family Law / CrPC","section":"CrPC 125","year":2021,"court":"Supreme Court of India","summary":"Comprehensive guidelines for maintenance to wife and child. Addressed overlapping maintenance claims in multiple proceedings.","judgement_text":"Only one maintenance application shall be decided and courts shall pass consolidated maintenance order. Income must be transparently disclosed.","keywords":"maintenance guidelines wife child crpc 125 consolidated order income disclosure overlapping proceedings"},
  {"title":"Shakti Vahini v. Union of India (2018)","act_name":"Constitutional Law","section":"Articles 19 21","year":2018,"court":"Supreme Court of India","summary":"Adult right to choose a spouse of their choice is fundamental right. Khap panchayats cannot interfere in consensual adult marriages.","judgement_text":"Right to choose a life partner is fundamental. Khap panchayats, family members or state cannot obstruct such choices without violating constitutional rights.","keywords":"honour killing khap panchayat love marriage inter-caste inter-religion consent adult rights article 21"},

  # ── Consumer Law ─────────────────────────────────────────────────────────
  {"title":"Spring Meadows Hospital v. Harjol Ahluwalia (1998)","act_name":"Consumer Protection Act","section":"Medical Negligence","year":1998,"court":"Supreme Court of India","summary":"Hospital and doctors are service providers under Consumer Protection Act. Medical negligence is deficiency in service.","judgement_text":"Negligence by hospital or doctor amounts to deficiency in service. Consumer forums have jurisdiction over medical negligence complaints.","keywords":"medical negligence hospital doctor consumer forum deficiency service compensation consumer protection act"},
  {"title":"National Insurance Co. v. Hindustan Safety Glass Works (2017)","act_name":"Consumer Protection Act","section":"Insurance Claim","year":2017,"court":"Supreme Court of India","summary":"Insurance company cannot repudiate claim on technical grounds without adequate investigation. Wrongful repudiation is deficiency in service.","judgement_text":"Insurance claim cannot be rejected on flimsy grounds. Once premium is paid, insurer is obligated to honor valid claims.","keywords":"insurance claim repudiation deficiency service consumer forum premium policy rejection technical grounds"},
  {"title":"Lucknow Development Authority v. M.K. Gupta (1994)","act_name":"Consumer Protection Act","section":"Deficiency of Service","year":1994,"court":"Supreme Court of India","summary":"Government agencies providing housing are service providers under CPA. Can be sued in consumer forum for delay in delivery.","judgement_text":"A government body allotting a house is a service provider. Failure to deliver on time or defects in housing are deficiencies in service.","keywords":"housing authority flat allotment delay consumer forum government service provider deficiency compensation"},
  {"title":"Chandigarh Housing Board v. Avtar Singh (2010)","act_name":"Consumer Protection Act","section":"Housing Dispute","year":2010,"court":"SC and NCDRC","summary":"Housing boards must refund money with interest if they fail to complete construction and hand over possession within agreed time.","judgement_text":"Payment of interest on refund is mandatory when authority fails to deliver possession. Rate of interest should be realistic to compensate loss.","keywords":"housing board flat refund interest delay possession construction incomplete consumer protection ncdrc"},
  {"title":"M/s Emaar MGF Land v. Aftab Singh (2018)","act_name":"Consumer Protection Act / RERA","section":"Real Estate Dispute","year":2018,"court":"Supreme Court of India","summary":"Consumer forums have jurisdiction over real estate disputes. Buyers of flats are consumers under Consumer Protection Act.","judgement_text":"A flat buyer who purchases property for personal use is a consumer. Deficiency in service by builder includes delay in delivery and construction defects.","keywords":"flat buyer consumer real estate builder delay possession deficiency rera consumer forum jurisdiction"},
  {"title":"Harsolia Motors v. National Insurance (2005)","act_name":"Consumer Protection Act","section":"Insurance","year":2005,"court":"NCDRC","summary":"Business entities cannot claim consumer status for insurance disputes if services are used for commercial purposes.","judgement_text":"A person purchasing insurance for commercial vehicle used in business is not a consumer under CPA as services are commercial in nature.","keywords":"consumer commercial purpose insurance vehicle business exclusion definition CPA jurisdiction forum"},
  {"title":"IRCTC v. N. Nagaraju (2016)","act_name":"Consumer Protection Act","section":"Railway Services","year":2016,"court":"NCDRC","summary":"Railways are service providers under Consumer Protection Act. Failure to provide booked berth or overbooking is deficiency of service.","judgement_text":"IRCTC providing reservation services is a service provider. Overbooking or denial of confirmed berth entitles passenger to compensation.","keywords":"railway irctc berth reservation overbooking refund ticket consumer deficiency service passenger compensation"},
  {"title":"Sapient Corporation v. Surendra Prasad (2012)","act_name":"Consumer Protection Act","section":"Employment Dispute","year":2012,"court":"NCDRC","summary":"Employment related disputes are not consumer disputes. An employee cannot file complaint against employer under Consumer Protection Act.","judgement_text":"Employer-employee relationship does not constitute service and consumer relationship under CPA. Such disputes are excluded from consumer forums.","keywords":"employment dispute employer employee consumer forum exclusion jurisdiction CPA service definition"},
  {"title":"Tata Motors v. Antonio Paulo Vaz (2021)","act_name":"Consumer Protection Act","section":"Product Liability","year":2021,"court":"Supreme Court of India","summary":"Manufacturer is liable for product defects causing harm. Consumer can claim compensation for manufacturing defect in vehicle.","judgement_text":"Product liability extends to manufacturer, seller, and distributor. Consumer is entitled to replacement, refund, or compensation for manufacturing defects.","keywords":"product liability car vehicle defect manufacturer compensation consumer protection 2019 act replacement refund"},
  {"title":"Shrikant Bichve v. Maharashtra Govt (2022)","act_name":"Consumer Protection Act 2019","section":"E-commerce Rules","year":2022,"court":"Maharashtra Consumer Commission","summary":"E-commerce platforms are responsible for goods sold on their platform. Cannot disclaim all liability for third-party sellers.","judgement_text":"E-commerce entity cannot completely insulate itself from liability. Platform has responsibility to ensure sellers deliver genuine products.","keywords":"ecommerce amazon flipkart platform liability seller consumer protection fake product online shopping"},

  # ── Cyber Law ────────────────────────────────────────────────────────────
  {"title":"Avnish Bajaj v. State (NCT of Delhi) (2005)","act_name":"IT Act 2000","section":"Section 67","year":2005,"court":"Delhi HC","summary":"E-commerce website operator cannot be held liable for obscene content posted by third-party users without knowledge.","judgement_text":"An intermediary website is not liable for third-party obscene content if it had no knowledge and took action after notice.","keywords":"it act section 67 intermediary liability obscene content ecommerce website online third party knowledge"},
  {"title":"P. Sivaswamy v. State (2019)","act_name":"IT Act 2000","section":"Section 66C 66D","year":2019,"court":"Madras HC","summary":"Using another person's digital identity for financial fraud is punishable under IT Act. SIM swapping is a cyberfraud.","judgement_text":"Identity theft using electronic means and cheating through personation online constitute offences under Sections 66C and 66D IT Act.","keywords":"identity theft sim swap section 66c 66d it act fraud online digital impersonation banking cyber"},
  {"title":"Jayesh v. State of Maharashtra (2017)","act_name":"IT Act 2000","section":"Section 65 66","year":2017,"court":"Bombay HC","summary":"Hacking into computer system without authorization is a cognizable offence. Digital evidence from CCTV must be properly authenticated.","judgement_text":"Hacking into computer without authorization under Section 66 IT Act is punishable with imprisonment up to 3 years and fine.","keywords":"hacking computer unauthorized access section 66 it act cybercrime digital forensics evidence authentication"},
  {"title":"Bankim Chandra Malhotra v. State of Gujarat (2022)","act_name":"IT Act / IPC","section":"Section 354D IPC Cyber Stalking","year":2022,"court":"Gujarat HC","summary":"Cyberstalking including sending repeated unwanted messages, monitoring online activity, and hacking email is punishable.","judgement_text":"Cyber stalking through repeated online messages, emails and monitoring constitutes stalking under IPC 354D and IT Act.","keywords":"cyberstalking section 354d ipc online harassment email messages monitoring social media it act women"},
  {"title":"Shreya Singhal v. Union of India (2015)","act_name":"IT Act 2000","section":"Section 69A","year":2015,"court":"Supreme Court of India","summary":"Section 69A website blocking upheld as constitutional but procedural safeguards required. Blocking must be reasonable and proportionate.","judgement_text":"Section 69A is constitutionally valid as it contains procedural safeguards for website blocking. Blocking must be specific not wholesale.","keywords":"section 69a website blocking it act constitutional procedural safeguard proportionate specific url"},
  {"title":"Raghav Jain v. State of Delhi (2020)","act_name":"IT Act / POCSO","section":"Section 67B IT Act","year":2020,"court":"Delhi HC","summary":"Sharing child sexual abuse material online is an aggravated offence under both IT Act Section 67B and POCSO Act.","judgement_text":"Any person storing, transmitting or publishing child sexual abuse material is guilty under Section 67B IT Act and POCSO. Bail is restricted.","keywords":"child pornography csam section 67b it act pocso online sharing images videos minor bail restricted"},
  {"title":"State of Tamil Nadu v. Suhas Katti (2004)","act_name":"IT Act 2000","section":"Section 67","year":2004,"court":"Chief Judicial Magistrate Chennai","summary":"First conviction under IT Act 2000 in India. Accused convicted for posting obscene messages about a woman on Yahoo groups.","judgement_text":"First conviction under IT Act. Posting obscene messages about known woman online violates her dignity and is punishable under Section 67.","keywords":"it act first conviction obscene message online email yahoo woman reputation harassment cyber crime chennai"},
  {"title":"Ritu Kohli Case (2001)","act_name":"IT Act 2000","section":"Section 66","year":2001,"court":"Chief Judicial Magistrate Delhi","summary":"First case of cyber stalking in India. Accused gave victim's phone number and address in online chat rooms posting sexual invitations.","judgement_text":"Posting a woman's phone number with sexual invitation in chat rooms is gross harassment and cyber stalking amounting to criminal offence.","keywords":"cyber stalking first case india it act online harassment chat room phone number woman victim sexual"},
  {"title":"National Crime Records Data Leakage Case (2018)","act_name":"IT Act 2000 / Indian Evidence Act","section":"Section 43 66","year":2018,"court":"Delhi HC","summary":"Government authority responsible for data breach must compensate affected individuals. Data protection is a statutory and constitutional obligation.","judgement_text":"Data protection is part of right to privacy. Unauthorized access to or leakage of personal data renders data controller liable.","keywords":"data breach data protection personal information government agency liability compensation privacy it act"},
  {"title":"Google India v. Vishaka Industries (2012)","act_name":"IT Act 2000","section":"Intermediary Guidelines","year":2012,"court":"AP HC","summary":"Search engines as intermediaries are not liable for defamatory content in search results if they act on takedown notice within due time.","judgement_text":"Search engine is an intermediary and not a publisher. Immunity exists under IT Act provided search engine responds to takedown requests expeditiously.","keywords":"google search engine intermediary liability notice takedown defamation IT act 2000 section 79 immunity"},

  # ── Labour & Employment Law ──────────────────────────────────────────────
  {"title":"Air India v. Nargesh Meerza (1981)","act_name":"Constitution of India","section":"Articles 14 and 16","year":1981,"court":"Supreme Court of India","summary":"Rule requiring air hostesses to retire on pregnancy was unconstitutional gender discrimination. Service conditions cannot discriminate on pregnancy.","judgement_text":"Making pregnancy a ground for termination violates Articles 14 and 16. Such conditions are manifestly arbitrary and discriminatory against women.","keywords":"air hostess pregnancy retirement gender discrimination article 14 16 employment condition unconstitutional maternity"},
  {"title":"Workmen of Dimakuchi Tea Estate v. Management (1958)","act_name":"Industrial Disputes Act","section":"Section 2(s)","year":1958,"court":"Supreme Court of India","summary":"Defined workman under Industrial Disputes Act. Supervisory employees doing predominantly manual or technical work are workmen.","judgement_text":"A person is a workman if he performs manual, unskilled, skilled, technical, operational, clerical or supervisory work.","keywords":"workman definition industrial disputes act supervisory manual technical clerical iDA retrenchment"},
  {"title":"ESIC v. Hyderabad Race Club (2004)","act_name":"Employees State Insurance Act","section":"ESIC Coverage","year":2004,"court":"AP HC","summary":"Employees of race clubs are entitled to ESI benefits. All establishments employing 10 or more persons are covered.","judgement_text":"ESI coverage extends to all establishments employing 10 or more persons in industry. Race clubs are establishments under the ESI Act.","keywords":"esic employees state insurance coverage establishment 10 employees provident fund social security benefit"},
  {"title":"Steel Authority of India v. National Union Waterfront Workers (2001)","act_name":"Contract Labour Act","section":"Regularization","year":2001,"court":"Supreme Court of India","summary":"Abolition of contract system does not automatically regularize contract workers. Absorption requires specific order by appropriate authority.","judgement_text":"When contract labour is abolished, contract workers do not automatically become direct employees. Regularization requires specific rules.","keywords":"contract labour regularization abolition statutory order CLRA Act direct employment casual worker"},
  {"title":"Parry and Co. v. P.C. Pal (1970)","act_name":"Industrial Employment Standing Orders Act","section":"Termination","year":1970,"court":"Supreme Court of India","summary":"Termination of workman without following standing orders and giving natural justice is void and illegal.","judgement_text":"A workman cannot be dismissed without following the certified standing orders and without being given opportunity of being heard.","keywords":"termination dismissal standing orders natural justice opportunity heard workman industrial employment"},
  {"title":"L. Robert D'Souza v. Executive Engineer (1982)","act_name":"Payment of Wages Act","section":"Section 7","year":1982,"court":"Supreme Court of India","summary":"Wages must be paid in full without any unauthorized deductions. Deductions only permitted as prescribed under Payment of Wages Act.","judgement_text":"Employer cannot make deductions from wages except those specified under Payment of Wages Act. Full wages are a right of the employee.","keywords":"wages payment deduction unauthorized employer employee rights payment of wages act section 7 salary"},
  {"title":"Bangalore Water Supply v. A. Rajappa (1978)","act_name":"Industrial Disputes Act","section":"Section 2(j)","year":1978,"court":"Supreme Court of India","summary":"Defined industry under IDA. Charitable, government, educational institutions can be industries if they carry on systematic economic activity.","judgement_text":"Industry includes any business, trade, undertaking, manufacture or calling with organized labour and employer-employee relationship.","keywords":"industry definition IDA section 2j charitable institution government services employees systematic activity"},
  {"title":"M/S Bharat Fire Works v. Ayub Khan (2019)","act_name":"Labour Law / Factories Act","section":"Compensation","year":2019,"court":"MP HC","summary":"Factory workers injured due to workplace accident entitled to full compensation under Employees Compensation Act including bonus.","judgement_text":"Employer is liable for full compensation for workplace injury. Compensation must include pay for disablement and medical expenses.","keywords":"workplace injury accident factory compensation employees compensation act disability payment medical"},
  {"title":"Reserve Bank of India v. Peerless General Finance (1987)","act_name":"SEBI / Employment Law","section":"Services Tribunal","year":1987,"court":"Supreme Court of India","summary":"Service conditions of public sector bank employees regulated by statutory provisions. Arbitrary changes to service rules are not permissible.","judgement_text":"Service conditions cannot be unilaterally altered by employer in public sector. Statutory rules govern employee-management relations.","keywords":"public sector employee service conditions statutory rules bank employment RBI change unilateral"},
  {"title":"Mackinnon Mackenzie v. Audrey D'Costa (1987)","act_name":"Equal Remuneration Act","section":"Section 4","year":1987,"court":"Supreme Court of India","summary":"Equal pay for equal work means workers performing same work must get same wages. Gender-based pay disparity is unconstitutional.","judgement_text":"Equal remuneration for equal work is a constitutional mandate. Men and women performing identical work must receive same wages.","keywords":"equal pay gender male female remuneration same work constitutional article 14 39 discrimination salary"},

  # ── Banking & Finance ────────────────────────────────────────────────────
  {"title":"Mardia Chemicals v. Union of India (2004)","act_name":"SARFAESI Act","section":"Section 13","year":2004,"court":"Supreme Court of India","summary":"Upheld constitutional validity of SARFAESI Act allowing banks to recover dues without court intervention while protecting borrower rights.","judgement_text":"SARFAESI Act is constitutional but borrower must be given notice and opportunity to represent before assets are auctioned.","keywords":"sarfaesi bank recovery loan default NPA asset auction notice borrower section 13 constitutional"},
  {"title":"Punjab National Bank v. De Borselli (2019)","act_name":"Insolvency and Bankruptcy Code","section":"IBC Section 7","year":2019,"court":"NCLT Mumbai","summary":"Financial creditor can initiate insolvency proceedings for default of minimum Rs 1 lakh. Admission triggers moratorium.","judgement_text":"On filing under Section 7 IBC and proof of default, NCLT must admit the insolvency petition within 14 days and declare moratorium.","keywords":"ibc insolvency financial creditor default loan NPA moratorium NCLT resolution professional section 7"},
  {"title":"Phoenix Arc v. Spade Financial (2021)","act_name":"IBC","section":"Section 31","year":2021,"court":"NCLAT","summary":"Resolution plan once approved by CoC and NCLT is binding on all creditors including dissenting financial creditors.","judgement_text":"Approved resolution plan binds all stakeholders including dissenting creditors. No party can challenge approved plan except for fraud or statutory violations.","keywords":"ibc resolution plan committee of creditors approved binding dissenting creditor insolvency NCLT"},
  {"title":"Keshav Prasad Gupta v. State of UP (2016)","act_name":"FEMA","section":"Section 13","year":2016,"court":"Allahabad HC","summary":"Remittance of foreign exchange beyond RBI set limits without approval constitutes violation of FEMA. Penalties are substantial.","judgement_text":"Contravention of FEMA provisions by remitting excess foreign exchange without approval attracts penalty up to three times the amount.","keywords":"fema foreign exchange remittance violation RBI approval penalty illegal outward transfer financial crime"},
  {"title":"Shivam Water Treaters v. Union of India (2011)","act_name":"Banking Regulation Act","section":"Bank Guarantee","year":2011,"court":"Gujarat HC","summary":"Unconditional bank guarantee must be honored without looking into disputes between the parties on the underlying contract.","judgement_text":"An unconditional bank guarantee is a primary obligation. Bank must pay on demand without inquiring into contract disputes.","keywords":"bank guarantee unconditional payment demand performance security letter of credit independent contract"},
  {"title":"Standard Chartered Bank v. Directorate of Enforcement (2005)","act_name":"FEMA/FERA","section":"Enforcement","year":2005,"court":"Supreme Court of India","summary":"Foreign banks operating in India are subject to FEMA regulations. Transactions without RBI approval can attract penalties.","judgement_text":"Foreign banks operating in India must comply with FEMA and RBI directives. Unauthorized foreign exchange transactions attract enforcement proceedings.","keywords":"foreign bank FEMA RBI compliance enforcement penalty foreign exchange authorized dealer currency"},
  {"title":"HDFC Bank v. J.J. Mannan (2010)","act_name":"Negotiable Instruments Act","section":"Section 138","year":2010,"court":"Supreme Court of India","summary":"Dishonour of cheque is a criminal offence. Accused can be convicted even without actual financial loss if cheque bounced for insufficient funds.","judgement_text":"Section 138 NI Act creates a strict liability offence. Dishonour of cheque for insufficient funds is an offence even without proving financial loss.","keywords":"cheque bounce dishonour section 138 NI act criminal offence insufficient funds bank payment conviction notice"},
  {"title":"Canara Bank v. N.G. Subbaraya Setty (2018)","act_name":"SARFAESI Act","section":"Section 14","year":2018,"court":"Supreme Court of India","summary":"Chief Metropolitan Magistrate has power to assist banks in taking possession of secured assets under SARFAESI without litigation.","judgement_text":"Court under Section 14 SARFAESI must assist secured creditor in taking actual possession of mortgaged property. This is a ministerial function.","keywords":"sarfaesi section 14 possession magistrate secured creditor mortgage property bank assist NPA loan"},
  {"title":"Laxmi Pat Surana v. Union Bank of India (2021)","act_name":"IBC","section":"Section 94","year":2021,"court":"Supreme Court of India","summary":"Personal guarantors of corporate debtors under IBC are separately liable and can be brought under insolvency proceedings.","judgement_text":"A personal guarantor who has given guarantee for corporate debtor's loan is an individual debtor under IBC and can face insolvency proceedings.","keywords":"personal guarantor corporate debtor IBC section 94 insolvency individual loan bank liability separate proceedings"},
  {"title":"Vijay Kumar Ghai v. State of West Bengal (2022)","act_name":"Prevention of Money Laundering Act","section":"PMLA Section 3","year":2022,"court":"Calcutta HC","summary":"Money laundering requires proof of predicate offence. Properties attached must be traceable to crime proceeds.","judgement_text":"For PMLA offence, prosecution must establish a scheduled offence and that the property attached represents proceeds of crime.","keywords":"pmla money laundering predicate offence proceeds crime ED attachment property arrest scheduled offence"},

  # ── Environmental Law ────────────────────────────────────────────────────
  {"title":"Vellore Citizens Welfare Forum v. Union of India (1996)","act_name":"Environment Protection Act","section":"Polluter Pays Principle","year":1996,"court":"Supreme Court of India","summary":"Applied Polluter Pays Principle and Precautionary Principle to tannery pollution in Tamil Nadu. Industries ordered to pay compensation.","judgement_text":"Polluter Pays Principle means the absolute liability for harm to the environment extends not just to compensate victims but also to restore environment.","keywords":"polluter pays principle precautionary environment tannery tamil nadu compensation restoration ecology water"},
  {"title":"MC Mehta v. Kamal Nath (1997)","act_name":"Environmental Law","section":"Public Trust Doctrine","year":1997,"court":"Supreme Court of India","summary":"Applied Public Trust Doctrine to rivers and forests. Government cannot lease public natural resources to private parties for commercial exploitation.","judgement_text":"The State as trustee of natural resources like rivers, air, forests must protect them for public use. Cannot be leased for private commercial gain.","keywords":"public trust doctrine river forest natural resources lease private commercial government trustee MC Mehta"},
  {"title":"Research Foundation for Science v. Union of India (2005)","act_name":"Hazardous Waste Rules","section":"Environment Protection","year":2005,"court":"Supreme Court of India","summary":"Import of hazardous waste including end-of-life ships must comply with environmental norms. Ship breaking must protect workers and environment.","judgement_text":"Import of waste ships must follow Hazardous Waste Rules. Workers at ship breaking yards must be provided safety equipment and protection.","keywords":"hazardous waste ship breaking import environment protection workers safety alang gujarat rules"},
  {"title":"Hanuman Laxman Aroskar v. Union of India (2019)","act_name":"Environment Protection Act","section":"EIA Notification","year":2019,"court":"Supreme Court of India","summary":"Environmental Impact Assessment is mandatory for projects affecting sensitive ecosystems. Granting clearance without EIA is illegal.","judgement_text":"EIA clearance cannot be given without following due procedure. Projects affecting Western Ghats biodiversity zone require enhanced scrutiny.","keywords":"environmental impact assessment EIA clearance goa airport western ghats biodiversity ecology forest"},
  {"title":"T.N. Godavarman Thirumulpad v. Union of India (1995)","act_name":"Forest Conservation Act","section":"Forest Protection","year":1995,"court":"Supreme Court of India","summary":"Ongoing case monitoring all forest-related activities across India. No non-forest activity can be carried out in forest land without Central permission.","judgement_text":"Any non-forest activity in forest land requires prior approval of Central Government under Forest Conservation Act. Courts have monitoring power.","keywords":"forest conservation act godavarman encroachment non-forest activity SC monitoring committee biodiversity national park"},
  {"title":"Indian Council for Enviro-Legal Action v. Union of India (1996)","act_name":"Environment Protection Act","section":"Absolute Liability","year":1996,"court":"Supreme Court of India","summary":"Chemical factories polluting groundwater ordered to pay compensation applying Absolute Liability principle. Remediation of site ordered.","judgement_text":"Industries using hazardous chemicals that pollute groundwater are absolutely liable to compensate affected communities and restore the environment.","keywords":"absolute liability chemical industry groundwater pollution compensation community restoration hazardous substance"},
  {"title":"Almitra H. Patel v. Union of India (2000)","act_name":"Municipal Solid Waste Rules","section":"Environmental Law","year":2000,"court":"Supreme Court of India","summary":"Directed municipalities to follow solid waste management rules. Landfills must not be in flood plains. Waste segregation is mandatory.","judgement_text":"Municipal authorities must provide door-to-door garbage collection, waste segregation, and scientific disposal. Unscientific landfills must be closed.","keywords":"solid waste management municipal garbage landfill segregation dumping contamination environment pollution india"},
  {"title":"Goa Foundation v. Sesa Sterlite (2014)","act_name":"Mines and Minerals Act","section":"Iron Ore Mining","year":2014,"court":"Supreme Court of India","summary":"Cancelled all iron ore mining leases in Goa for failure to obtain renewals and environmental violations. Ordered rehabilitation fund.","judgement_text":"Mining without valid environmental clearance and lease renewal is illegal. All such mining operations must cease and fund be created for rehabilitation.","keywords":"iron ore mining goa lease cancellation environmental clearance rehabilitation fund pollution ecology forest"},
  {"title":"Sterlite Industries v. Union of India (2013)","act_name":"Environment Protection Act","section":"Industrial Pollution","year":2013,"court":"Supreme Court of India","summary":"Upheld closure of Sterlite copper plant for serious environmental violations and pollution causing public health crisis.","judgement_text":"Persistent violation of environmental norms and causing public health emergency justifies closure of industrial plant under Environment Protection Act.","keywords":"sterlite copper plant closure tuticorin pollution environment public health emergency industrial emissions norms"},
  {"title":"Noise Pollution Case (Church of God in India v. KKR) (2000)","act_name":"Environment Protection Act","section":"Noise Pollution Rules","year":2000,"court":"Supreme Court of India","summary":"No religious group has right to create noise nuisance. Loudspeakers and loud music violate right to decent environment and peaceful living.","judgement_text":"No religion mandates use of loudspeakers or creation of noise pollution. Use of loud sound systems violates Noise Pollution Rules.","keywords":"noise pollution loudspeaker religious decibel limits environment nuisance residents right peaceful living church mosque temple"},

  # ── Tort & Negligence ────────────────────────────────────────────────────
  {"title":"Bhim Singh v. State of J&K (1985)","act_name":"Constitutional Law","section":"Article 21","year":1985,"court":"Supreme Court of India","summary":"MLA illegally detained and prevented from attending Assembly session. State ordered to pay compensation for unlawful detention.","judgement_text":"Compensation for illegal detention is a constitutional remedy. Courts can award monetary compensation under public law for fundamental rights violation.","keywords":"compensation illegal detention MLA assembly session fundamental rights writ public law monetary remedy"},
  {"title":"Indian Airlines Corporation v. Madhuri Chaudhuri (1965)","act_name":"Tort Law","section":"Negligence","year":1965,"court":"Calcutta HC","summary":"Airline held liable for injury to passenger due to negligent procedure during boarding. Contributory negligence can reduce compensation.","judgement_text":"Carrier has duty of care towards passenger. Negligence resulting in injury entitles passenger to compensation. Contributory negligence reduces amount.","keywords":"airline negligence passenger injury duty of care carrier contributory compensation tort damages boarding"},
  {"title":"Jacob Mathew v. State of Punjab (2005)","act_name":"IPC / Medical Law","section":"IPC 304A","year":2005,"court":"Supreme Court of India","summary":"High standard of proof required to convict doctor for criminal negligence. Mere error of judgment is not criminal negligence.","judgement_text":"Criminal negligence by doctor requires gross departure from accepted medical practice. Mere error of judgment does not constitute criminal rashness.","keywords":"medical negligence doctor criminal ipc 304a error judgment gross departure standard care hospital doctor conviction"},
  {"title":"M.A. Muruganandam v. S. Sethupathy (2018)","act_name":"Motor Vehicles Act","section":"Accident Compensation","year":2018,"court":"Madras HC","summary":"Motor accident victims entitled to compensation based on structured formula. Multiplier method applied to calculate future loss of earnings.","judgement_text":"Motor Accidents Claims Tribunal must apply structured formula including multiplier method to calculate fair compensation for death and disability.","keywords":"motor accident compensation tribunal MACT claim multiplier formula death disability future earnings injury"},
  {"title":"National Insurance Co. v. Pranay Sethi (2017)","act_name":"Motor Vehicles Act","section":"Section 166","year":2017,"court":"Supreme Court of India","summary":"Comprehensive guidelines for uniform calculation of motor accident compensation including future prospects and conventional heads.","judgement_text":"Future prospects must be added to income of victim. Non-pecuniary damages include pain suffering and loss of amenities of life.","keywords":"motor accident compensation formula future prospects pecuniary non-pecuniary loss consortium income multiplier uniform"},
  {"title":"Rajkot Municipal Corporation v. Manjulaben Jayantilal (2018)","act_name":"Constitutional Law / Tort","section":"State Liability","year":2018,"court":"Supreme Court of India","summary":"Municipal corporation is liable for negligence in maintaining public roads. Potholes causing accidents attract state liability.","judgement_text":"State through its instrumentalities has duty to maintain roads in safe condition. Failure resulting in accident makes the state vicariously liable.","keywords":"municipal corporation road pothole accident negligence state liability compensation tort public road maintenance"},
  {"title":"Mohori Bibee v. Dharmodas Ghose (1903)","act_name":"Contract Act","section":"Section 11","year":1903,"court":"Privy Council","summary":"Contract with a minor is void ab initio. Minor cannot be sued for enforcement of contract or for restitution of benefits under void contract.","judgement_text":"A minor is incompetent to contract. Any agreement with a minor is void from the very beginning. No estoppel can be raised against a minor.","keywords":"minor contract void ab initio incompetent person section 11 contract act restitution incapacity estoppel"},
  {"title":"State of Haryana v. Smt. Santra (2000)","act_name":"Constitutional Law","section":"Right to Compensation","year":2000,"court":"Supreme Court of India","summary":"Wrongful sterilization by government hospital results in right to compensation for the woman. State is liable for medical negligence.","judgement_text":"Failed sterilization by government hospital resulting in unwanted pregnancy entitles woman to compensation from the state under public law.","keywords":"sterilization failure medical negligence government hospital compensation woman pregnancy state liability public health"},

  # ── Intellectual Property ────────────────────────────────────────────────
  {"title":"Novartis AG v. Union of India (2013)","act_name":"Patents Act","section":"Section 3(d)","year":2013,"court":"Supreme Court of India","summary":"Rejected patent application for cancer drug Gleevec. Section 3(d) prevents evergreening of pharmaceutical patents.","judgement_text":"Section 3(d) prevents evergreening of pharmaceutical patents. Incremental changes to known molecule that don't show enhanced efficacy are not patentable.","keywords":"patent gleevec novartis pharmaceutical section 3d evergreening drugs cancer patent rejection efficacy india"},
  {"title":"Bajaj Auto v. TVS Motor Company (2009)","act_name":"Patents Act","section":"Patent Infringement","year":2009,"court":"Supreme Court of India","summary":"Laid down principles for interim injunction in patent disputes. Injunction requires prima facie case, balance of convenience, and irreparable harm.","judgement_text":"In patent disputes, court must examine whether patented invention is novel and non-obvious. Three tests for interim injunction must be applied.","keywords":"patent infringement interim injunction bajaj TVS motor vehicle technology prima facie irreparable harm balance"},
  {"title":"Entertainment Network India v. Super Cassette (2008)","act_name":"Copyright Act","section":"Section 31 License","year":2008,"court":"Supreme Court of India","summary":"Broadcast organizations entitled to compulsory license for musical works if owner refuses to grant license on reasonable terms.","judgement_text":"Compulsory license under Copyright Act can be granted when copyright owner refuses to grant license on reasonable terms to broadcast organizations.","keywords":"copyright compulsory license broadcast radio station music owner refusal reasonable terms section 31"},
  {"title":"Cadbury India v. Neeraj Food Products (2007)","act_name":"Trademarks Act","section":"Trademark Infringement","year":2007,"court":"Delhi HC","summary":"DAIRY MILK trademark belonging to Cadbury cannot be used by competitor. Passing off action protects established goodwill.","judgement_text":"Using a well-known trademark causes consumer confusion and damages owner's goodwill. Passing off requires proof of goodwill, misrepresentation, and damage.","keywords":"trademark infringement dairy milk cadbury passing off goodwill consumer confusion competing product section 29"},
  {"title":"Micromax v. Nokia (2014)","act_name":"Competition Act / Patents","section":"FRAND License","year":2014,"court":"Competition Commission of India","summary":"Nokia alleged to have abused dominance by charging excessive royalties for standard essential patents. CCI examined FRAND licensing.","judgement_text":"Standard essential patent holders must license on FRAND terms. Excessive royalties or refusal to license can constitute abuse of dominant position.","keywords":"standard essential patent FRAND license royalties nokia micromax CCI competition dominance abuse mobile telecom"},
  {"title":"Anil Gupta v. Kunal Dasgupta (2002)","act_name":"Copyright Act","section":"Section 13","year":2002,"court":"Delhi HC","summary":"Marriage bureau business idea translated into TV format is protectable expression not mere idea. Copyright exists in original expression.","judgement_text":"Copyright protects expression not ideas. The format, scheme and structure of a TV show can be copyrighted as original literary or dramatic work.","keywords":"copyright tv format show idea expression protected swayamvar television marriage original creative work"},
  {"title":"Time Incorporated v. Lokesh Srivastava (2005)","act_name":"Trademarks Act","section":"Well-Known Trademark","year":2005,"court":"Delhi HC","summary":"TIME trademark is a well-known mark. Unauthorized use on goods in unrelated field amounts to dilution and passing off.","judgement_text":"A well-known trademark like TIME has protection across all classes of goods and services. Use in unrelated field still amounts to dilution.","keywords":"time magazine trademark well known mark dilution passing off unrelated goods protection reputation Delhi HC"},
  {"title":"Sohail Faisal v. Union of India (2022)","act_name":"Geographical Indications Act","section":"GI Tag","year":2022,"court":"IPAB","summary":"Darjeeling Tea producers entitled to exclusive GI tag protection. Misleading use of GI in commerce constitutes infringement.","judgement_text":"Geographical Indication protecting Darjeeling Tea entitles all registered producers to exclusive use. Misuse is an infringement under GI Act.","keywords":"geographical indication GI tag darjeeling tea protection producers infringement misuse trade commerce registry"},

  # ── Tax Law ──────────────────────────────────────────────────────────────
  {"title":"Commissioner of Income Tax v. Vodafone International Holdings (2012)","act_name":"Income Tax Act","section":"Section 9","year":2012,"court":"Supreme Court of India","summary":"Offshore share transfer between two foreign entities was not taxable in India even if underlying assets were in India. Overturned Bombay HC.","judgement_text":"Transfer of shares of foreign company outside India not subject to Indian income tax even if underlying assets in India. No tax can be imposed retrospectively.","keywords":"vodafone income tax offshore transfer capital gains foreign company india tax out section 9 retrospective"},
  {"title":"CIT v. Sun Engineering Works (1992)","act_name":"Income Tax Act","section":"Business Deduction","year":1992,"court":"Supreme Court of India","summary":"Expenditure on capital account cannot be deducted as business expense. Revenue expenditure deductible. Distinction is fundamental to taxation.","judgement_text":"Capital expenditure increases earning capacity while revenue expenditure maintains it. Only revenue expenditure is deductible under IT Act.","keywords":"income tax capital expenditure revenue deduction business expense section 37 depreciation allowance profit"},
  {"title":"K.P. Varghese v. ITO (1981)","act_name":"Income Tax Act","section":"Capital Gains","year":1981,"court":"Supreme Court of India","summary":"Held that deemed consideration for tax on transfer of capital assets cannot exceed actual consideration received in case of genuine transactions.","judgement_text":"Tax on capital gains basis of deemed value cannot apply when property is transferred to relative without undervaluation.","keywords":"capital gains deemed value consideration property transfer income tax relative undervaluation section 52"},
  {"title":"Dharmendra Textile Processors v. CBDT (2008)","act_name":"Income Tax Act","section":"TDS Default","year":2008,"court":"Gujarat HC","summary":"Failure to deduct or deposit TDS attracts penalty even without mens rea. TDS deduction is a strict liability obligation.","judgement_text":"TDS default attracts strict penalty without requirement of proving mens rea. Assessee is duty bound to deduct and deposit tax at source.","keywords":"TDS tax deducted at source default penalty strict liability mens rea section 271C section 40a income tax"},
  {"title":"All India Federation of Tax Practitioners v. Union of India (2007)","act_name":"GST / Service Tax","section":"Constitutional Validity","year":2007,"court":"Supreme Court of India","summary":"Service tax on services is constitutionally valid. Parliament has residuary power to levy service tax under Entry 97.","judgement_text":"Service tax is valid under Entry 97 residuary list. Services are not covered by State List so Parliament competent to levy service tax.","keywords":"service tax constitutional validity parliament residuary entry 97 list state federal services GST"},
  {"title":"Union of India v. Azadi Bachao Andolan (2003)","act_name":"Income Tax Act / DTAA","section":"Tax Treaty","year":2003,"court":"Supreme Court of India","summary":"Provided treaty shopping through Mauritius route is not inherently invalid. Tax benefits under DTAA cannot be denied without anti-avoidance measures.","judgement_text":"Treaty shopping via Mauritius is not per se illegal. India-Mauritius DTAA benefit cannot be denied if investor has valid certificate of residence.","keywords":"mauritius route DTAA treaty shopping tax avoidance capital gains foreign investment double taxation income tax"},
  {"title":"M/s Ecom Gill Coffee Trading v. CBIC (2023)","act_name":"GST Act","section":"Input Tax Credit","year":2023,"court":"Karnataka HC","summary":"Buyer cannot be denied GST input tax credit merely because supplier has defaulted in payment of GST to government.","judgement_text":"Recipient of goods/services cannot be penalized for default of supplier in depositing GST. ITC denial to innocent buyer is unconstitutional.","keywords":"GST input tax credit ITC denial supplier default buyer innocent unconstitutional section 16 Karnataka HC"},
  {"title":"Assistant Commissioner of Commercial Tax v. Shukla (2022)","act_name":"GST Act","section":"Section 69 Arrest","year":2022,"court":"Allahabad HC","summary":"Arrest under GST Act requires cogent reasons. Mere evasion allegation without material evidence does not justify arrest.","judgement_text":"Power to arrest under GST Act must be exercised with caution. Arrest requires belief based on material evidence not mere suspicion of evasion.","keywords":"GST arrest evasion section 69 tax officer cognizable offence reasons material evidence bail allahabad"},

  # ── Immigration & Citizenship ────────────────────────────────────────────
  {"title":"Sarbananda Sonowal v. Union of India (2005)","act_name":"Illegal Migrants Act","section":"IMDT Act","year":2005,"court":"Supreme Court of India","summary":"Struck down Illegal Migrants (Determination by Tribunals) Act as unconstitutional. Burden of proving illegal migration placed on state.","judgement_text":"IMDT Act which reversed burden of proof for detecting illegal migrants in Assam was unconstitutional and struck down.","keywords":"illegal immigrant IMDT Assam NRC citizenship burden proof unconstitutional migration detention foreigners act"},
  {"title":"Prem Shankar Shukla v. Delhi Administration (1980)","act_name":"Constitution of India","section":"Article 21","year":1980,"court":"Supreme Court of India","summary":"Handcuffing of undertrial prisoners without compelling judicial necessity violates human dignity and Article 21.","judgement_text":"Handcuffing is a violation of human dignity. Prisoners can only be handcuffed in cases of special reasons recorded in writing.","keywords":"handcuffing prisoner undertrial article 21 dignity fundamental rights humanity custodial confinement police"},
  {"title":"National Human Rights Commission v. State of Arunachal Pradesh (1996)","act_name":"Constitutional Law","section":"Citizenship & Fundamental Rights","year":1996,"court":"Supreme Court of India","summary":"Chakma refugees titled to protection of life and personal liberty. State cannot expel them without following due process of law.","judgement_text":"Non-citizens including refugees are entitled to protection under Article 21. State cannot expel Chakma refugees without establishing legal basis.","keywords":"refugee chakma expulsion state article 21 non-citizen protection deportation fundamental rights due process"},
  {"title":"Mohammad Salimullah v. Union of India (2021)","act_name":"Citizenship Amendment Act","section":"CAA","year":2021,"court":"Supreme Court of India","summary":"SC examining constitutional validity of Citizenship Amendment Act 2019. Matter pending. Interim stay denied.","judgement_text":"Constitutional validity of CAA is a matter of substantial public importance pending hearing. No interim stay on operation of CAA granted.","keywords":"citizenship amendment act CAA NRC religion persecution Pakistan Bangladesh Afghanistan Hindu Muslim Sikh"},

  # ── Domestic Violence & Women Rights ────────────────────────────────────
  {"title":"S. Hanumantha Rao v. S. Ramani (1999)","act_name":"Hindu Marriage Act","section":"Matrimonial Cruelty","year":1999,"court":"AP HC","summary":"Husband's second marriage and bringing second wife home constitutes cruelty to first wife entitling her to divorce.","judgement_text":"Bringing a second wife into matrimonial home and ignoring first wife constitutes serious matrimonial cruelty. Divorce can be granted.","keywords":"second marriage bigamy cruelty first wife divorce section 13 hindu marriage act matrimonial harassment"},
  {"title":"Wazir Chand v. State of Haryana (1989)","act_name":"Dowry Prohibition Act","section":"Section 4","year":1989,"court":"Supreme Court of India","summary":"Demand for dowry by husband and in-laws is a criminal offence. Conviction under Dowry Prohibition Act sustained.","judgement_text":"Demand for dowry whether before, at or after marriage is an offence. Conviction of husband and in-laws for dowry demand is valid.","keywords":"dowry demand prohibition act marriage in-laws husband criminal offence section 4 conviction harassment arrest"},
  {"title":"Indra Sarma v. V.K.V. Sarma (2013)","act_name":"Domestic Violence Act 2005","section":"Live-in Relationship","year":2013,"court":"Supreme Court of India","summary":"Live-in relationships that resemble marriage over time may give the female partner domestic violence protection under DVA 2005.","judgement_text":"A woman in a long-term stable domestic relationship resembling marriage is a domestic relationship under DVA. She can seek protection orders.","keywords":"live-in relationship domestic violence act DVA woman partner protection relationship in nature of marriage"},
  {"title":"V.D. Bhanot v. Savita Bhanot (2012)","act_name":"Domestic Violence Act","section":"Shared Household","year":2012,"court":"Supreme Court of India","summary":"Protection order under DVA can be obtained by woman against husband even if she voluntarily left the shared household.","judgement_text":"DV Act protection extends even if woman has left shared household. Continuous violence in relationship need not occur at household.","keywords":"domestic violence protection order shared household left voluntarily relationship DVA husband wife section 2"},
  {"title":"Lalita Kumari v. State of Uttar Pradesh (2014)","act_name":"CrPC","section":"Section 154","year":2014,"court":"Supreme Court of India","summary":"Registration of FIR is mandatory in cognizable offences. Police cannot refuse to register FIR or conduct preliminary enquiry.","judgement_text":"Police are bound to register FIR when information reveals cognizable offence. Refusal to register FIR is violation of duty and law.","keywords":"FIR registration mandatory police cognizable offence section 154 crpc refuse complaint duty preliminary inquiry"},
  {"title":"Mukesh v. State (NCT of Delhi) (2017)","act_name":"IPC","section":"IPC 376 302","year":2017,"court":"Supreme Court of India","summary":"Nirbhaya case. Upheld death penalty for all four accused for brutal gang rape and murder of 23-year-old on Delhi bus in 2012.","judgement_text":"The brutality of gang rape and murder in this case places it in the rarest of rare category justifying death penalty for all accused.","keywords":"nirbhaya gang rape murder delhi bus death penalty section 376D 302 IPC brutality victim women safety"},
  {"title":"State of Punjab v. Gurmit Singh (1996)","act_name":"IPC","section":"IPC 376","year":1996,"court":"Supreme Court of India","summary":"In rape cases, conviction can be based solely on credible testimony of the victim. No corroboration required if her statement is trustworthy.","judgement_text":"Testimony of rape victim is entitled to credit. No corroboration required if the court finds victim reliable. Conviction based on victim's testimony alone is valid.","keywords":"rape victim testimony corroboration trustworthy conviction evidence section 376 IPC trial court appeal"},
  {"title":"Bhikari Jadav v. State of Odisha (2013)","act_name":"POCSO Act","section":"Section 4","year":2013,"court":"Orissa HC","summary":"Child sexual abuse cases under POCSO must be tried in designated special courts. Child's evidence recorded with care for trauma.","judgement_text":"POCSO courts must have child-friendly atmosphere. Cross examination of child victim must be through judge, not direct by defence.","keywords":"POCSO child sexual abuse special court evidence recording victim protection minor section 4 assault defence"},
  {"title":"Independent Thought v. Union of India (2017)","act_name":"IPC / POCSO","section":"Exception 2 to IPC 375","year":2017,"court":"Supreme Court of India","summary":"Sexual intercourse with child wife between 15-18 years is rape. Exception 2 to Section 375 IPC struck down as unconstitutional.","judgement_text":"Exception 2 to IPC 375 which allowed marital rape of girl between 15-18 years is inconsistent with POCSO Act and struck down.","keywords":"marital rape child wife 15 18 years pocso section 375 exception struck down unconstitutional husband minor"},

  # ── Contract & Commercial Law ────────────────────────────────────────────
  {"title":"Satyabrata Ghose v. Mugneeram Bangur (1954)","act_name":"Contract Act","section":"Section 56 Frustration","year":1954,"court":"Supreme Court of India","summary":"Doctrine of frustration of contract applies in India similar to common law. Contract becomes void if performance becomes impossible due to supervening events.","judgement_text":"Contract frustrated when supervening event makes performance impossible or fundamentally different from what was contracted. Lease frustrated by government acquisition.","keywords":"contract frustration section 56 impossible performance supervening event lease acquisition void discharge"},
  {"title":"Hadley v. Baxendale Applied in India Union of India v. Raman Iron Foundry (1974)","act_name":"Contract Act","section":"Section 73 Damages","year":1974,"court":"Supreme Court of India","summary":"Applied Hadley v Baxendale principles to Indian contract law. Only damages naturally arising or within contemplation of parties recoverable.","judgement_text":"Damages recoverable under contract are those arising naturally from breach or such as were reasonably foreseeable at time of contract.","keywords":"damages breach contract section 73 natural arising foreseeable hadley baxendale remoteness special loss"},
  {"title":"Khardah Company v. Raymon and Co. (India) (1962)","act_name":"Specific Relief Act","section":"Section 10","year":1962,"court":"Supreme Court of India","summary":"Specific performance of contract for sale of unique goods or immovable property may be decreed if damages are inadequate remedy.","judgement_text":"Specific performance is a discretionary remedy. Courts grant it when damages are not adequate compensation. Real property cases qualify.","keywords":"specific performance contract land property unique goods inadequate damages discretionary relief section 10 decree"},
  {"title":"M/S Trimex International FZE Ltd. v. Vedanta Aluminium Ltd. (2010)","act_name":"Arbitration and Conciliation Act","section":"Section 11","year":2010,"court":"Supreme Court of India","summary":"Arbitration clause in contract survives even if the contract is void. Arbitrability of a dispute is separate from validity of contract.","judgement_text":"An arbitration clause in a commercial contract is independent of other clauses. Even if contract is alleged void, arbitrator can decide disputes.","keywords":"arbitration clause commercial contract void separability agreement section 11 appointment arbitrator dispute"},
  {"title":"Associate Builders v. Delhi Development Authority (2014)","act_name":"Arbitration and Conciliation Act","section":"Section 34","year":2014,"court":"Supreme Court of India","summary":"Scope of court interference in arbitral awards limited. Award can only be set aside on grounds of patent illegality or public policy.","judgement_text":"Court cannot review arbitral award on merits. Patent illegality or conflict with public policy are the only grounds to set aside an award.","keywords":"arbitral award set aside section 34 patent illegality public policy interference merits review arbitration"},
  {"title":"Fateh Chand v. Balkishan Das (1963)","act_name":"Contract Act","section":"Section 74","year":1963,"court":"Supreme Court of India","summary":"Liquidated damages clause in contract is not penalty. Aggrieved party need not prove actual loss to claim pre-agreed sum.","judgement_text":"If parties pre-agree on sum payable for breach, claimant need not prove actual loss. Courts can however award lesser amount if loss is proven.","keywords":"liquidated damages penalty clause section 74 contract breach pre-agreed sum forfeit earnest money loss"},
  {"title":"Ranchi Electricity Supply Co. v. M/S Sumit Ply (2002)","act_name":"Electricity Act","section":"Service Contract","year":2002,"court":"Jharkhand HC","summary":"Electricity company cannot disconnect supply without due notice and opportunity to the consumer to rectify the default.","judgement_text":"Prior notice and opportunity to pay dues must be given before disconnecting electricity. Disconnection without notice is illegal.","keywords":"electricity disconnection notice consumer default payment dues opportunity CPA deficiency service supply"},

  # ── Miscellaneous High-Impact Cases ─────────────────────────────────────
  {"title":"S.P. Gupta v. Union of India (1982)","act_name":"Constitution of India","section":"Article 32 / Locus Standi","year":1982,"court":"Supreme Court of India","summary":"Expanded locus standi through PIL. Any public-spirited citizen can file PIL for enforcement of constitutional rights of others.","judgement_text":"Any member of public can maintain writ petition if public interest is involved. PIL is a tool for judicial enforcement of constitutional rights of masses.","keywords":"PIL public interest litigation locus standi article 32 fundamental rights citizens access court justice equality"},
  {"title":"BALCO Employees Union v. Union of India (2002)","act_name":"Industrial Disputes Act / Constitutional Law","section":"Disinvestment","year":2002,"court":"Supreme Court of India","summary":"Disinvestment of government companies is a policy decision. Courts cannot interfere in economic policy unless it violates fundamental rights.","judgement_text":"Disinvestment of PSUs is a policy decision within executive domain. Courts cannot strike down economic policy unless it violates constitutional provisions.","keywords":"disinvestment PSU privatization government company economic policy judicial review fundamental rights employee"},
  {"title":"Centre for PIL v. Union of India (Coal Scam) (2012)","act_name":"Constitutional Law / Mining","section":"Natural Resources","year":2012,"court":"Supreme Court of India","summary":"Coal block allocations without competitive bidding were illegal and arbitrary in violation of Article 14 right to equality.","judgement_text":"Distribution of natural resources must follow transparent and non-discriminatory process. Arbitrary allocation violates Article 14 and natural resource doctrine.","keywords":"coal scam allocation block coal gate mining article 14 equal treatment natural resource auction competitive"},
  {"title":"Prajatantrik Riti Morcha v. State of Rajasthan (2017)","act_name":"RTI Act","section":"Section 6","year":2017,"court":"Rajasthan HC","summary":"Government officials cannot refuse RTI applications without valid grounds. Frivolous rejection of RTI is contempt of the Act.","judgement_text":"RTI application must be decided within stipulated time. Refusal must state specific exemption. Denial of legitimate RTI is contempt.","keywords":"RTI right to information government official refusal exemption section 8 stipulated period transparency accountability"},
  {"title":"Union of India v. Tulsiram Patel (1985)","act_name":"Constitution of India","section":"Article 311","year":1985,"court":"Supreme Court of India","summary":"Government employee can be dismissed without full inquiry in cases of national security. Article 311(2)(c) exemption applies.","judgement_text":"Public employment can be terminated without departmental inquiry if Government considers holding of inquiry reasonably practicable or in interests of state security.","keywords":"government employee dismissal inquiry article 311 public service security exception natural justice termination"},
  {"title":"Motor General Traders v. State of A.P. (1984)","act_name":"Constitution of India","section":"Article 19(1)(g)","year":1984,"court":"Supreme Court of India","summary":"Right to carry on business includes right to sell all products lawfully made or obtained. Unreasonable restrictions are unconstitutional.","judgement_text":"Article 19(1)(g) guarantees right to trade. Any restriction must fall within Article 19(6) and must be reasonable. Restriction on selling liquor upheld.","keywords":"right to trade profession business article 19 1 g liquor restriction reasonable fundamental right license"},
  {"title":"People's Union for Civil Liberties v. Union of India (PUCL) (2003)","act_name":"Constitutional Law / POTA","year":2003,"section":"Section POTA","court":"Supreme Court of India","summary":"Upheld POTA terrorism law but directed strict oversight to prevent misuse. Confession to police officer made admissible under POTA challenged.","judgement_text":"Anti-terror law can make confession to senior police officer admissible. But safeguards must be in place to prevent coercion and misuse of the provision.","keywords":"POTA terrorism confession police admissible safeguard anti terror law national security fundamental rights misuse"},
  {"title":"A.K. Gopalan v. State of Madras (1950)","act_name":"Constitution of India","section":"Article 21","year":1950,"court":"Supreme Court of India","summary":"Early case interpreting Article 21. Held that procedure prescribed by law need not be just fair and reasonable — later overruled by Maneka Gandhi.","judgement_text":"Article 21 right to life is protected only against executive action, not legislative action. A law prescribing procedure is sufficient even if harsh.","keywords":"article 21 right to life liberty early case Maneka Gandhi overruled procedure law preventive detention AK Gopalan"},
  {"title":"CPIO Supreme Court v. Subhash Chandra Agarwal (2019)","act_name":"RTI Act","section":"Chief Justice Office","year":2019,"court":"Supreme Court of India","summary":"Office of the Chief Justice of India is a public authority under RTI Act. Information about judges' assets can be disclosed.","judgement_text":"The Supreme Court is a public authority under RTI Act. Transparency and accountability are essential for judicial institution. CJI office covered.","keywords":"RTI supreme court CJI chief justice public authority information judges assets transparency accountability judiciary"},
  {"title":"State of Bihar v. Kameshwar Singh (1952)","act_name":"Constitution of India / Land Reform","section":"Article 31A","year":1952,"court":"Supreme Court of India","summary":"Zamindari abolition laws are protected under Article 31A. Land reform laws cannot be challenged on grounds of violation of property rights.","judgement_text":"Land reform laws are saved by Article 31A. Zamindari abolition and vesting of land in state are protected from Article 14 and 19 challenge.","keywords":"zamindari abolition land reform article 31A property rights tenants Bihar land laws protection compensation"},
]

def seed_cases():
    with app.app_context():
        existing = LegalCase.query.count()
        print(f"\n=== LexGuard AI — Cases Seeder ===")
        print(f"Existing cases in DB: {existing}")

        if existing >= len(CASES):
            print(f"DB already has {existing} cases. Skipping seed.")
            return

        # Clear and re-seed for clean state
        print(f"Adding {len(CASES)} cases to DB...")
        LegalCase.query.delete()
        db.session.commit()

        for i, c in enumerate(CASES):
            case = LegalCase(**c)
            db.session.add(case)
            if (i + 1) % 50 == 0:
                db.session.flush()
                print(f"  {i+1} cases inserted...")

        db.session.commit()
        print(f"\n[OK] {len(CASES)} legal cases seeded successfully.\n")


if __name__ == "__main__":
    seed_cases()
